services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rosa_db
    ports:
      - "5435:5432"
    volumes:
      - db-data:/var/lib/postgresql

volumes:
  db-data:
